version: '3.7'

services:
  # PostgreSQLの実行環境
  postgresql:
    container_name: devenv_postgresql
    build:
      context: ./docker/postgresql
      dockerfile: Dockerfile
    image: devenv/postgresql
    ports:
      - 5432:5432
    networks:
      - container_link
    volumes:
      - postgresql_data:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_db
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --locale=C'

  # pgAdmin4の実行環境
  pgadmin4:
    container_name: devenv_pgadmin4
    image: dpage/pgadmin4:4.29
    depends_on:
      - postgresql
    ports:
      - 5433:80
    networks:
      - container_link
    volumes:
      - pgadmin4_data:/var/lib/pgadmin:rw
    environment:
      PGADMIN_DEFAULT_EMAIL: example@co.jp
      PGADMIN_DEFAULT_PASSWORD: password

  # Golangの実行環境
  app:
    container_name: devenv_app
    build:
      context: ./
      dockerfile: docker/app/Dockerfile
    image: devenv/golang
    depends_on:
      - postgresql
    networks:
      - container_link
    volumes:
      - ./:/go/src/app:rw
    tty: true

networks:
  default:
    external:
      name: bridge
  container_link:
    name: devenv.docker.internal

volumes:
  postgresql_data:
    driver: local
  pgadmin4_data:
    driver: local
